version: 2
build:
  os: "ubuntu-24.04"
  tools:
    python: "mambaforge-22.9"
  jobs:
    post_install:
      - pip install .
      - pip install .[docs] --extra-index-url=https://artefact.skao.int/repository/pypi-internal/simple
      - pip install .[postx]
conda:
  environment: environment.yml
sphinx:
  configuration: docs/src/conf.py
