# Prometheus configuration for DSA-110 Pipeline
global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "dsa110_rules.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

scrape_configs:
  # DSA-110 Pipeline metrics
  - job_name: 'dsa110-pipeline'
    static_configs:
      - targets: ['dsa110-pipeline:8080']
    scrape_interval: 30s
    metrics_path: '/metrics'
    
  # DSA-110 Monitoring service
  - job_name: 'dsa110-monitoring'
    static_configs:
      - targets: ['dsa110-monitoring:8082']
    scrape_interval: 30s
    metrics_path: '/metrics'
    
  # Redis metrics
  - job_name: 'redis'
    static_configs:
      - targets: ['dsa110-redis:6379']
    scrape_interval: 30s
    
  # Node exporter (if available)
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 30s
