import React from "react";
import {
  Box,
  Card,
  CardContent,
  Typography,
  Grid,
  Chip,
  Alert,
  Table,
  TableBody,
  TableCell,
  TableContainer,
  TableHead,
  TableRow,
  Paper,
} from "@mui/material";
import { BarChart } from "@mui/icons-material";
import { alpha } from "@mui/material/styles";
import { useEventStatistics } from "../../api/queries";
import { SkeletonLoader } from "../SkeletonLoader";
import { EmptyState } from "../EmptyState";

export default function EventStats() {
  const { data: stats, isLoading, error } = useEventStatistics();

  if (error) {
    return (
      <Alert severity="error">
        Failed to load event statistics: {error instanceof Error ? error.message : "Unknown error"}
      </Alert>
    );
  }

  if (isLoading) {
    return <SkeletonLoader variant="cards" rows={4} />;
  }

  if (!stats) {
    return (
      <EmptyState
        icon={<BarChart sx={{ fontSize: 64, color: "text.secondary" }} />}
        title="No statistics available"
        description="Event statistics will appear here once events have been generated by the pipeline. Check the event stream to see current activity."
      />
    );
  }

  return (
    <Card>
      <CardContent>
        <Typography variant="h6" gutterBottom>
          Event Statistics
        </Typography>

        <Grid container spacing={2} sx={{ mb: 3 }}>
          <Grid xs={12} sm={6} md={3}>
            <Card variant="outlined">
              <CardContent>
                <Typography variant="body2" color="text.secondary">
                  Total Events
                </Typography>
                <Typography variant="h4">{stats.total_events.toLocaleString()}</Typography>
              </CardContent>
            </Card>
          </Grid>

          <Grid xs={12} sm={6} md={3}>
            <Card variant="outlined">
              <CardContent>
                <Typography variant="body2" color="text.secondary">
                  Events in History
                </Typography>
                <Typography variant="h4">{stats.events_in_history.toLocaleString()}</Typography>
              </CardContent>
            </Card>
          </Grid>

          <Grid xs={12} sm={6} md={3}>
            <Card variant="outlined">
              <CardContent>
                <Typography variant="body2" color="text.secondary">
                  Last Minute
                </Typography>
                <Typography variant="h4">{stats.events_last_minute.toLocaleString()}</Typography>
              </CardContent>
            </Card>
          </Grid>

          <Grid xs={12} sm={6} md={3}>
            <Card variant="outlined">
              <CardContent>
                <Typography variant="body2" color="text.secondary">
                  Last Hour
                </Typography>
                <Typography variant="h4">{stats.events_last_hour.toLocaleString()}</Typography>
              </CardContent>
            </Card>
          </Grid>
        </Grid>

        {/* Events by Type */}
        <Typography variant="subtitle1" gutterBottom>
          Events by Type
        </Typography>
        <TableContainer
          component={Paper}
          sx={{
            "& .MuiTable-root": {
              "& .MuiTableHead-root .MuiTableRow-root": {
                backgroundColor: "background.paper",
                "& .MuiTableCell-head": {
                  fontWeight: 600,
                  backgroundColor: "action.hover",
                },
              },
              "& .MuiTableBody-root .MuiTableRow-root": {
                "&:nth-of-type(even)": {
                  backgroundColor: alpha("#fff", 0.02),
                },
                "&:hover": {
                  backgroundColor: "action.hover",
                  cursor: "default",
                },
                transition: "background-color 0.2s ease",
              },
            },
          }}
        >
          <Table size="small">
            <TableHead>
              <TableRow>
                <TableCell>Event Type</TableCell>
                <TableCell align="right">Count</TableCell>
              </TableRow>
            </TableHead>
            <TableBody>
              {Object.entries(stats.events_per_type || {}).map(([type, count]) => (
                <TableRow key={type}>
                  <TableCell>
                    <Chip label={type} size="small" />
                  </TableCell>
                  <TableCell align="right">{count.toLocaleString()}</TableCell>
                </TableRow>
              ))}
            </TableBody>
          </Table>
        </TableContainer>

        {/* Subscribers */}
        {stats.subscribers && Object.keys(stats.subscribers).length > 0 && (
          <>
            <Typography variant="subtitle1" gutterBottom sx={{ mt: 3 }}>
              Subscribers
            </Typography>
            <TableContainer
              component={Paper}
              sx={{
                "& .MuiTable-root": {
                  "& .MuiTableHead-root .MuiTableRow-root": {
                    backgroundColor: "background.paper",
                    "& .MuiTableCell-head": {
                      fontWeight: 600,
                      backgroundColor: "action.hover",
                    },
                  },
                  "& .MuiTableBody-root .MuiTableRow-root": {
                    "&:nth-of-type(even)": {
                      backgroundColor: alpha("#fff", 0.02),
                    },
                    "&:hover": {
                      backgroundColor: "action.hover",
                      cursor: "default",
                    },
                    transition: "background-color 0.2s ease",
                  },
                },
              }}
            >
              <Table size="small">
                <TableHead>
                  <TableRow>
                    <TableCell>Event Type</TableCell>
                    <TableCell align="right">Subscribers</TableCell>
                  </TableRow>
                </TableHead>
                <TableBody>
                  {Object.entries(stats.subscribers).map(([type, count]) => (
                    <TableRow key={type}>
                      <TableCell>
                        <Chip label={type} size="small" />
                      </TableCell>
                      <TableCell align="right">{count}</TableCell>
                    </TableRow>
                  ))}
                </TableBody>
              </Table>
            </TableContainer>
          </>
        )}
      </CardContent>
    </Card>
  );
}
