database:
  host: localhost
  max_overflow: 20
  name: dsa110_pipeline
  pool_recycle: 3600
  pool_size: 10
  pool_timeout: 30
  port: 5432
  ssl_mode: prefer
  user: dsa110
debug: false
environment: production
monitoring:
  dashboard_port: 8081
  enable_grafana: true
  enable_prometheus: true
  enabled: true
  grafana_port: 8083
  health_check_interval: 30
  log_backup_count: 5
  log_file: /app/logs/pipeline.log
  log_format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
  log_level: INFO
  log_max_size: 100MB
  metrics_port: 8080
  prometheus_port: 8082
pipeline: {}
redis:
  db: 0
  health_check_interval: 30
  host: localhost
  max_connections: 100
  port: 6379
  retry_on_timeout: true
  socket_connect_timeout: 5
  socket_timeout: 5
resources:
  cache_size: 2Gi
  cache_ttl: 3600
  cleanup_interval: 300
  max_concurrent_tasks: 4
  max_cpu: 4000m
  max_memory: 8Gi
  task_timeout: 3600
  temp_dir: /tmp/dsa110
security:
  cors_origins: []
  enable_https: false
  jwt_expiration: 3600
  rate_limit: 100
  rate_limit_window: 60
