# config/environments/production.yaml
"""
Production environment configuration for DSA-110 pipeline.

This configuration is optimized for production use with full
data volumes and optimized performance settings.
"""

# Base configuration
base_config: &base_config
  # Paths
  paths:
    log_dir: "/data/dsa110/pipeline/logs"
    ms_stage1_dir: "/data/dsa110/ms_stage1"
    cal_tables_dir: "/data/dsa110/cal_tables"
    skymodels_dir: "/data/dsa110/skymodels"
    images_dir: "/data/dsa110/images"
    mosaics_dir: "/data/dsa110/mosaics"
    photometry_dir: "/data/dsa110/photometry"
    hdf5_dir: "/data/dsa110/hdf5"
  
  # Services
  services:
    mosaic_duration_min: 60
    mosaic_overlap_min: 10
    ms_chunk_duration_min: 5
    max_concurrent_blocks: 4
  
  # Calibration
  calibration:
    fixed_declination_deg: 37.0
    gcal_refant: "pad001"
    gcal_mode: "ap"
    gcal_solint: "30min"
    gcal_minsnr: 3.0
    gcal_uvrange: ""
    flagging:
      tfcrop_timecutoff: 4.0
      tfcrop_freqcutoff: 4.0
  
  # Imaging
  imaging:
    deconvolver: "hogbom"
    gridder: "wproject"
    wprojplanes: -1
    niter: 5000
    threshold: "1mJy"
    interactive: false
    image_size: [4800, 4800]
    cell_size: "3arcsec"
    weighting: "briggs"
    robust: 0.5
    pblimit: 0.1
    pbcor: true
    savemodel: "modelcolumn"
    use_clean_mask: true
    save_fits: true
  
  # Mosaicking
  mosaicking:
    mosaic_type: "optimal"
    mosaic_nx: 28800
    mosaic_ny: 4800
    mosaic_cell: "3arcsec"
    save_fits: true
  
  # Photometry
  photometry:
    detection:
      fwhm_pixels: 3.0
      threshold_sigma: 5.0
    classification:
      target_flux_range: [0.001, 0.1]
      reference_flux_range: [0.01, 1.0]
      min_separation_arcsec: 30.0
    aperture:
      radius_arcsec: 3.0
      inner_annulus_arcsec: 6.0
      outer_annulus_arcsec: 9.0
  
  # Sky model
  skymodel:
    field:
      radius_deg: 0.5
      n_sources: 100
    flux:
      min_flux_jy: 0.001
      max_flux_jy: 1.0
      power_law_index: -1.5
  
  # MS creation
  ms_creation:
    test_mode: false
    n_antennas: 110
    n_frequencies: 64
    n_times: 100

# Production-specific overrides
production:
  <<: *base_config
  
  # Production logging
  logging:
    level: "INFO"
    console_output: false
    file_output: true
  
  # Optimized for production
  services:
    mosaic_duration_min: 60
    mosaic_overlap_min: 10
    ms_chunk_duration_min: 5
    max_concurrent_blocks: 4
  
  # Full resolution imaging
  imaging:
    image_size: [4800, 4800]
    niter: 5000
    threshold: "1mJy"
    use_clean_mask: true
  
  mosaicking:
    mosaic_nx: 28800
    mosaic_ny: 4800
  
  skymodel:
    field:
      n_sources: 100
  
  ms_creation:
    n_antennas: 110
    n_frequencies: 64
    n_times: 100
