# Service Configuration for DSA-110 Pipeline
# Environment-specific service settings

development:
  services:
    # HDF5 Watcher Service
    hdf5_watcher:
      enabled: true
      poll_interval_sec: 60
      expected_subbands: 12
      file_pattern: "20*T*.hdf5"
      processing_timeout_sec: 300
    
    # MS Processor Service
    ms_processor:
      enabled: true
      poll_interval_sec: 120
      mosaic_duration_min: 60
      mosaic_overlap_min: 5
      ms_chunk_duration_min: 5
      processing_timeout_sec: 1800
    
    # Variability Analyzer Service
    variability_analyzer:
      enabled: true
      analysis_interval_hours: 1
      min_data_points: 10
      variability_threshold: 0.1
      analysis_timeout_sec: 600
    
    # Service Manager
    service_manager:
      enabled: true
      health_check_interval_sec: 30
      service_restart_attempts: 3
      service_restart_delay_sec: 10

production:
  services:
    # HDF5 Watcher Service
    hdf5_watcher:
      enabled: true
      poll_interval_sec: 30
      expected_subbands: 12
      file_pattern: "20*T*.hdf5"
      processing_timeout_sec: 600
    
    # MS Processor Service
    ms_processor:
      enabled: true
      poll_interval_sec: 60
      mosaic_duration_min: 60
      mosaic_overlap_min: 5
      ms_chunk_duration_min: 5
      processing_timeout_sec: 3600
    
    # Variability Analyzer Service
    variability_analyzer:
      enabled: true
      analysis_interval_hours: 0.5
      min_data_points: 5
      variability_threshold: 0.05
      analysis_timeout_sec: 1200
    
    # Service Manager
    service_manager:
      enabled: true
      health_check_interval_sec: 15
      service_restart_attempts: 5
      service_restart_delay_sec: 5

testing:
  services:
    # HDF5 Watcher Service
    hdf5_watcher:
      enabled: true
      poll_interval_sec: 120
      expected_subbands: 4
      file_pattern: "20*T*.hdf5"
      processing_timeout_sec: 60
    
    # MS Processor Service
    ms_processor:
      enabled: true
      poll_interval_sec: 300
      mosaic_duration_min: 10
      mosaic_overlap_min: 1
      ms_chunk_duration_min: 2
      processing_timeout_sec: 300
    
    # Variability Analyzer Service
    variability_analyzer:
      enabled: true
      analysis_interval_hours: 0.25
      min_data_points: 3
      variability_threshold: 0.2
      analysis_timeout_sec: 120
    
    # Service Manager
    service_manager:
      enabled: true
      health_check_interval_sec: 60
      service_restart_attempts: 2
      service_restart_delay_sec: 5

# Redis Configuration for Distributed State and Messaging
redis:
  host: "localhost"
  port: 6379
  db: 0
  password: null
  max_connections: 10
  socket_timeout: 5
  socket_connect_timeout: 5
  retry_on_timeout: true
  health_check_interval: 30

# Message Queue Configuration
messaging:
  redis:
    host: "localhost"
    port: 6379
    db: 1
    password: null
  queues:
    hdf5_processing: "hdf5_processing"
    ms_processing: "ms_processing"
    variability_analysis: "variability_analysis"
    system: "system"
  message_ttl: 3600
  consumer_timeout: 5

# Monitoring Configuration
monitoring:
  health_check_interval: 30
  metrics_retention_days: 7
  alert_thresholds:
    service_down_time_minutes: 5
    processing_failure_rate: 0.1
    memory_usage_percent: 80
    disk_usage_percent: 90
