#!/bin/bash
# Monthly Anti-Pattern Review Script
# Extracts patterns from mistake log and identifies recurring anti-patterns

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
MISTAKE_LOG="$ROOT_DIR/MISTAKE_LOG.md"
TECHNICAL_DEBT="$ROOT_DIR/TECHNICAL_DEBT.md"
REVIEW_OUTPUT="$ROOT_DIR/ANTI_PATTERN_REVIEW_$(date +%Y-%m).md"

# Colors
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

echo "=== Monthly Anti-Pattern Review ==="
echo "Date: $(date)"
echo ""

# Extract patterns from mistake log
echo "Analyzing mistake log..."

if [ ! -f "$MISTAKE_LOG" ]; then
  echo "Mistake log not found: $MISTAKE_LOG"
  exit 1
fi

# Extract mistake types
MISTAKE_TYPES=$(grep -E "^\[MISTAKE\]" "$MISTAKE_LOG" | sed 's/\[MISTAKE\] //' | cut -d: -f1 | sort | uniq -c | sort -rn)

# Extract root causes
ROOT_CAUSES=$(grep -E "Root cause:" "$MISTAKE_LOG" | sed 's/.*Root cause: //' | sort | uniq -c | sort -rn)

# Extract prevention strategies
PREVENTIONS=$(grep -E "Prevention:" "$MISTAKE_LOG" | sed 's/.*Prevention: //' | sort | uniq -c | sort -rn)

# Generate review report
cat > "$REVIEW_OUTPUT" << EOF
# Anti-Pattern Review - $(date +%Y-%m)

Generated: $(date)

## Summary

### Mistakes Analyzed
$(grep -c "^\[MISTAKE\]" "$MISTAKE_LOG" || echo "0")

### Unique Mistake Types
$(echo "$MISTAKE_TYPES" | wc -l)

## Top Mistake Types

\`\`\`
$MISTAKE_TYPES
\`\`\`

## Common Root Causes

\`\`\`
$ROOT_CAUSES
\`\`\`

## Prevention Strategies

\`\`\`
$PREVENTIONS
\`\`\`

## Recurring Anti-Patterns

### Identified Patterns

$(grep -E "\[MISTAKE\].*dismiss\|rationalize\|ignore" "$MISTAKE_LOG" | head -5 | sed 's/^/- /')

## Recommendations

### High Priority
- [ ] Address most common mistake types
- [ ] Implement prevention strategies
- [ ] Update guidelines based on patterns

### Medium Priority
- [ ] Review and refactor recurring issues
- [ ] Add detection for common patterns
- [ ] Improve documentation

### Low Priority
- [ ] Monitor for new patterns
- [ ] Share learnings with team
- [ ] Update training materials

## Next Steps

1. Review this report
2. Prioritize improvements
3. Assign to sprints
4. Update technical debt log
5. Implement prevention measures

---

*Generated by anti-pattern-review.sh*
EOF

echo -e "${GREEN}Review report generated:${NC} $REVIEW_OUTPUT"
echo ""
echo "Top mistake types:"
echo "$MISTAKE_TYPES" | head -5
echo ""
echo "Next: Review $REVIEW_OUTPUT and update $TECHNICAL_DEBT"

