"""Initial baseline - stamp existing schema.

This migration serves as a baseline marker for the existing database schema.
It doesn't make any changes - it just marks the current schema as "initial"
so that future autogenerated migrations can be applied incrementally.

To stamp an existing database with this baseline:
    DATABASE=products alembic stamp head

Revision ID: 0001_baseline
Revises: 
Create Date: 2025-11-29
"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '0001_baseline'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    """Baseline migration - no changes.
    
    The database schema already exists. This migration exists solely
    to provide a known starting point for future migrations.
    
    If you're running this on a new database, the tables should be
    created via:
        from dsa110_contimg.database.session import init_database
        init_database("products")
    """
    pass


def downgrade() -> None:
    """No downgrade from baseline."""
    pass
