"""Initial products schema

Revision ID: ad58b1d1c97a
Revises: 
Create Date: 2025-11-29 01:36:18.148157

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ad58b1d1c97a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('astrometric_solutions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_astrometry_applied'))
        batch_op.drop_index(batch_op.f('idx_astrometry_mosaic'))

    op.drop_table('astrometric_solutions')
    with op.batch_alter_table('image_qa', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_img_qa_ms_path'))

    op.drop_table('image_qa')
    with op.batch_alter_table('ese_candidates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_ese_flagged'))
        batch_op.drop_index(batch_op.f('idx_ese_source'))
        batch_op.drop_index(batch_op.f('idx_ese_status'))

    op.drop_table('ese_candidates')
    with op.batch_alter_table('alert_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_alert_sent'))
        batch_op.drop_index(batch_op.f('idx_alert_source'))
        batch_op.drop_index(batch_op.f('idx_alert_type'))

    op.drop_table('alert_history')
    with op.batch_alter_table('data_relationships', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_data_relationships_child'))
        batch_op.drop_index(batch_op.f('idx_data_relationships_parent'))

    op.drop_table('data_relationships')
    with op.batch_alter_table('variability_stats', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_variability_chi2'))
        batch_op.drop_index(batch_op.f('idx_variability_eta'))
        batch_op.drop_index(batch_op.f('idx_variability_last_mjd'))
        batch_op.drop_index(batch_op.f('idx_variability_sigma'))

    op.drop_table('variability_stats')
    with op.batch_alter_table('calibration_qa', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_cal_qa_ms_path'))

    op.drop_table('calibration_qa')
    with op.batch_alter_table('regions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_regions_created'))
        batch_op.drop_index(batch_op.f('idx_regions_image'))
        batch_op.drop_index(batch_op.f('idx_regions_type'))

    op.drop_table('regions')
    with op.batch_alter_table('transient_alerts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_alerts_candidate'))
        batch_op.drop_index(batch_op.f('idx_alerts_level'))
        batch_op.drop_index(batch_op.f('idx_alerts_status'))

    op.drop_table('transient_alerts')
    with op.batch_alter_table('astrometric_residuals', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_residuals_solution'))

    op.drop_table('astrometric_residuals')
    with op.batch_alter_table('transient_lightcurves', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_lightcurves_candidate'))

    op.drop_table('transient_lightcurves')
    with op.batch_alter_table('data_tags', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_data_tags_data_id'))

    op.drop_table('data_tags')
    with op.batch_alter_table('cross_matches', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_cross_matches_catalog'))
        batch_op.drop_index(batch_op.f('idx_cross_matches_created'))
        batch_op.drop_index(batch_op.f('idx_cross_matches_master'))
        batch_op.drop_index(batch_op.f('idx_cross_matches_quality'))
        batch_op.drop_index(batch_op.f('idx_cross_matches_source'))

    op.drop_table('cross_matches')
    with op.batch_alter_table('mosaics', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_mosaics_created'))
        batch_op.drop_index(batch_op.f('idx_mosaics_mjd'))

    op.drop_table('mosaics')
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_jobs_created'))
        batch_op.drop_index(batch_op.f('idx_jobs_status'))

    op.drop_table('jobs')
    with op.batch_alter_table('data_registry', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_data_registry_finalization'))
        batch_op.drop_index(batch_op.f('idx_data_registry_published_at'))
        batch_op.drop_index(batch_op.f('idx_data_registry_status'))
        batch_op.drop_index(batch_op.f('idx_data_registry_type_status'))

    op.drop_table('data_registry')
    with op.batch_alter_table('batch_job_items', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
        batch_op.alter_column('ms_path',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
        batch_op.alter_column('status',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
        batch_op.alter_column('started_at',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True)
        batch_op.drop_index(batch_op.f('idx_batch_items_batch_id'))
        batch_op.drop_index(batch_op.f('idx_batch_items_ms_path'))
        batch_op.drop_column('data_id')
        batch_op.drop_column('completed_at')

    with op.batch_alter_table('batch_jobs', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
        batch_op.alter_column('type',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
        batch_op.alter_column('created_at',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=False)
        batch_op.alter_column('status',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)

    with op.batch_alter_table('calibrator_transits', schema=None) as batch_op:
        batch_op.alter_column('calibrator_name',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
        batch_op.alter_column('transit_mjd',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=False)
        batch_op.alter_column('transit_iso',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
        batch_op.alter_column('group_id',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
        batch_op.alter_column('group_mid_iso',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
        batch_op.alter_column('delta_minutes',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True)
        batch_op.alter_column('pb_response',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True)
        batch_op.alter_column('calculated_at',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=False)
        batch_op.alter_column('updated_at',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=False)

    with op.batch_alter_table('dead_letter_queue', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
        batch_op.alter_column('component',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
        batch_op.alter_column('operation',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
        batch_op.alter_column('error_type',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
        batch_op.alter_column('created_at',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=False)
        batch_op.alter_column('status',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True,
               existing_server_default=sa.text("'pending'"))
        batch_op.alter_column('resolved_at',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True)

    with op.batch_alter_table('hdf5_file_index', schema=None) as batch_op:
        batch_op.alter_column('path',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               nullable=False)
        batch_op.alter_column('filename',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
        batch_op.alter_column('group_id',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
        batch_op.alter_column('subband_code',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
        batch_op.alter_column('timestamp_iso',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
        batch_op.alter_column('timestamp_mjd',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True)
        batch_op.alter_column('modified_time',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True)
        batch_op.alter_column('indexed_at',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=False)

    with op.batch_alter_table('images', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
        batch_op.alter_column('path',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
        batch_op.alter_column('ms_path',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
        batch_op.alter_column('created_at',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=False)
        batch_op.alter_column('type',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
        batch_op.alter_column('beam_major_arcsec',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True)
        batch_op.alter_column('beam_minor_arcsec',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True)
        batch_op.alter_column('beam_pa_deg',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True)
        batch_op.alter_column('noise_jy',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True)
        batch_op.alter_column('format',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True,
               existing_server_default=sa.text('("fits")'))
        batch_op.alter_column('dynamic_range',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True)
        batch_op.alter_column('field_name',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
        batch_op.alter_column('center_ra_deg',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True)
        batch_op.alter_column('center_dec_deg',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True)
        batch_op.alter_column('cellsize_arcsec',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True)
        batch_op.alter_column('freq_ghz',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True)
        batch_op.alter_column('bandwidth_mhz',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True)
        batch_op.alter_column('integration_sec',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True)
        batch_op.drop_index(batch_op.f('idx_images_field'))

    with op.batch_alter_table('monitoring_sources', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
        batch_op.alter_column('source_id',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
        batch_op.alter_column('ra_deg',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=False)
        batch_op.alter_column('dec_deg',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=False)
        batch_op.alter_column('mean_flux_jy',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True)
        batch_op.alter_column('std_flux_jy',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True)
        batch_op.alter_column('eta',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True)
        batch_op.alter_column('v_index',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True)
        batch_op.alter_column('first_detected_at',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True)
        batch_op.alter_column('last_detected_at',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True)
        batch_op.drop_column('catalog')
        batch_op.drop_column('name')
        batch_op.drop_column('priority')
        batch_op.drop_column('notes')
        batch_op.drop_column('last_updated')
        batch_op.drop_column('chi_squared')

    with op.batch_alter_table('ms_index', schema=None) as batch_op:
        batch_op.alter_column('path',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               nullable=False)
        batch_op.alter_column('start_mjd',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True)
        batch_op.alter_column('end_mjd',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True)
        batch_op.alter_column('mid_mjd',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True)
        batch_op.alter_column('processed_at',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True)
        batch_op.alter_column('status',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
        batch_op.alter_column('stage',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
        batch_op.alter_column('stage_updated_at',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True)
        batch_op.alter_column('imagename',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
        batch_op.alter_column('ra_deg',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True)
        batch_op.alter_column('dec_deg',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True)
        batch_op.alter_column('field_name',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
        batch_op.alter_column('pointing_ra_deg',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True)
        batch_op.alter_column('pointing_dec_deg',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True)
        batch_op.drop_index(batch_op.f('idx_ms_index_field'))
        batch_op.drop_index(batch_op.f('idx_ms_index_mjd'))

    with op.batch_alter_table('photometry', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
        batch_op.alter_column('source_id',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
        batch_op.alter_column('image_path',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
        batch_op.alter_column('ra_deg',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=False)
        batch_op.alter_column('dec_deg',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=False)
        batch_op.alter_column('nvss_flux_mjy',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True)
        batch_op.alter_column('peak_jyb',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=False)
        batch_op.alter_column('peak_err_jyb',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True)
        batch_op.alter_column('measured_at',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=False)
        batch_op.alter_column('snr',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True)
        batch_op.alter_column('mjd',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True)
        batch_op.alter_column('flux_jy',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True)
        batch_op.alter_column('flux_err_jy',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True)
        batch_op.alter_column('normalized_flux_jy',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True)
        batch_op.alter_column('normalized_flux_err_jy',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True)
        batch_op.alter_column('mosaic_path',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
        batch_op.alter_column('sep_from_center_deg',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True)
        batch_op.drop_index(batch_op.f('idx_photometry_source_mjd'))

    with op.batch_alter_table('storage_locations', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
        batch_op.alter_column('location_type',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
        batch_op.alter_column('base_path',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
        batch_op.alter_column('description',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
        batch_op.alter_column('registered_at',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=False)
        batch_op.alter_column('status',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True,
               existing_server_default=sa.text("'active'"))
        batch_op.alter_column('notes',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)

    with op.batch_alter_table('transient_candidates', schema=None) as batch_op:
        batch_op.add_column(sa.Column('source_id', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('priority', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('n_detections', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('mean_flux_jy', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('std_flux_jy', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('eta', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('v_index', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('chi_squared', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('is_variable', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('ese_candidate', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('first_detected_at', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('last_detected_at', sa.Float(), nullable=True))
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
        batch_op.alter_column('ra_deg',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=False)
        batch_op.alter_column('dec_deg',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=False)
        batch_op.alter_column('detection_type',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               nullable=False)
        batch_op.alter_column('significance_sigma',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True)
        batch_op.alter_column('detected_at',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               nullable=True)
        batch_op.alter_column('last_updated',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True)
        batch_op.drop_index(batch_op.f('idx_transient_ms_path'))
        batch_op.drop_index(batch_op.f('idx_transient_timestamp'))
        batch_op.drop_column('classification')
        batch_op.drop_column('rms_mjy')
        batch_op.drop_column('mosaic_id')
        batch_op.drop_column('flux_baseline_mjy')
        batch_op.drop_column('baseline_catalog')
        batch_op.drop_column('image_path')
        batch_op.drop_column('snr')
        batch_op.drop_column('timestamp_mjd')
        batch_op.drop_column('flux_obs_mjy')
        batch_op.drop_column('source_name')
        batch_op.drop_column('variability_index')
        batch_op.drop_column('flux_ratio')
        batch_op.drop_column('ms_path')
        batch_op.drop_column('peak_mjy')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transient_candidates', schema=None) as batch_op:
        batch_op.add_column(sa.Column('peak_mjy', sa.REAL(), nullable=False))
        batch_op.add_column(sa.Column('ms_path', sa.TEXT(), nullable=False))
        batch_op.add_column(sa.Column('flux_ratio', sa.REAL(), nullable=True))
        batch_op.add_column(sa.Column('variability_index', sa.REAL(), nullable=True))
        batch_op.add_column(sa.Column('source_name', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('flux_obs_mjy', sa.REAL(), nullable=True))
        batch_op.add_column(sa.Column('timestamp_mjd', sa.REAL(), nullable=True))
        batch_op.add_column(sa.Column('snr', sa.REAL(), nullable=False))
        batch_op.add_column(sa.Column('image_path', sa.TEXT(), nullable=False))
        batch_op.add_column(sa.Column('baseline_catalog', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('flux_baseline_mjy', sa.REAL(), nullable=True))
        batch_op.add_column(sa.Column('mosaic_id', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('rms_mjy', sa.REAL(), nullable=False))
        batch_op.add_column(sa.Column('classification', sa.TEXT(), nullable=True))
        batch_op.create_index(batch_op.f('idx_transient_timestamp'), ['timestamp_mjd'], unique=False)
        batch_op.create_index(batch_op.f('idx_transient_ms_path'), ['ms_path'], unique=False)
        batch_op.alter_column('last_updated',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True)
        batch_op.alter_column('detected_at',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               nullable=False)
        batch_op.alter_column('significance_sigma',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True)
        batch_op.alter_column('detection_type',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('dec_deg',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=False)
        batch_op.alter_column('ra_deg',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=False)
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
        batch_op.drop_column('last_detected_at')
        batch_op.drop_column('first_detected_at')
        batch_op.drop_column('ese_candidate')
        batch_op.drop_column('is_variable')
        batch_op.drop_column('chi_squared')
        batch_op.drop_column('v_index')
        batch_op.drop_column('eta')
        batch_op.drop_column('std_flux_jy')
        batch_op.drop_column('mean_flux_jy')
        batch_op.drop_column('n_detections')
        batch_op.drop_column('priority')
        batch_op.drop_column('source_id')

    with op.batch_alter_table('storage_locations', schema=None) as batch_op:
        batch_op.alter_column('notes',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('status',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True,
               existing_server_default=sa.text("'active'"))
        batch_op.alter_column('registered_at',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=False)
        batch_op.alter_column('description',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('base_path',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
        batch_op.alter_column('location_type',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    with op.batch_alter_table('photometry', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_photometry_source_mjd'), ['source_id', 'mjd'], unique=False)
        batch_op.alter_column('sep_from_center_deg',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True)
        batch_op.alter_column('mosaic_path',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('normalized_flux_err_jy',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True)
        batch_op.alter_column('normalized_flux_jy',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True)
        batch_op.alter_column('flux_err_jy',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True)
        batch_op.alter_column('flux_jy',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True)
        batch_op.alter_column('mjd',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True)
        batch_op.alter_column('snr',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True)
        batch_op.alter_column('measured_at',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=False)
        batch_op.alter_column('peak_err_jyb',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True)
        batch_op.alter_column('peak_jyb',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=False)
        batch_op.alter_column('nvss_flux_mjy',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True)
        batch_op.alter_column('dec_deg',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=False)
        batch_op.alter_column('ra_deg',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=False)
        batch_op.alter_column('image_path',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
        batch_op.alter_column('source_id',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    with op.batch_alter_table('ms_index', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_ms_index_mjd'), ['mid_mjd'], unique=False)
        batch_op.create_index(batch_op.f('idx_ms_index_field'), ['field_name'], unique=False)
        batch_op.alter_column('pointing_dec_deg',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True)
        batch_op.alter_column('pointing_ra_deg',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True)
        batch_op.alter_column('field_name',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('dec_deg',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True)
        batch_op.alter_column('ra_deg',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True)
        batch_op.alter_column('imagename',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('stage_updated_at',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True)
        batch_op.alter_column('stage',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('status',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('processed_at',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True)
        batch_op.alter_column('mid_mjd',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True)
        batch_op.alter_column('end_mjd',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True)
        batch_op.alter_column('start_mjd',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True)
        batch_op.alter_column('path',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=True)

    with op.batch_alter_table('monitoring_sources', schema=None) as batch_op:
        batch_op.add_column(sa.Column('chi_squared', sa.REAL(), nullable=True))
        batch_op.add_column(sa.Column('last_updated', sa.REAL(), nullable=True))
        batch_op.add_column(sa.Column('notes', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('priority', sa.TEXT(), server_default=sa.text("'normal'"), nullable=True))
        batch_op.add_column(sa.Column('name', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('catalog', sa.TEXT(), nullable=True))
        batch_op.alter_column('last_detected_at',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True)
        batch_op.alter_column('first_detected_at',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True)
        batch_op.alter_column('v_index',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True)
        batch_op.alter_column('eta',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True)
        batch_op.alter_column('std_flux_jy',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True)
        batch_op.alter_column('mean_flux_jy',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True)
        batch_op.alter_column('dec_deg',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=False)
        batch_op.alter_column('ra_deg',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=False)
        batch_op.alter_column('source_id',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    with op.batch_alter_table('images', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_images_field'), ['field_name'], unique=False)
        batch_op.alter_column('integration_sec',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True)
        batch_op.alter_column('bandwidth_mhz',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True)
        batch_op.alter_column('freq_ghz',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True)
        batch_op.alter_column('cellsize_arcsec',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True)
        batch_op.alter_column('center_dec_deg',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True)
        batch_op.alter_column('center_ra_deg',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True)
        batch_op.alter_column('field_name',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('dynamic_range',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True)
        batch_op.alter_column('format',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True,
               existing_server_default=sa.text('("fits")'))
        batch_op.alter_column('noise_jy',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True)
        batch_op.alter_column('beam_pa_deg',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True)
        batch_op.alter_column('beam_minor_arcsec',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True)
        batch_op.alter_column('beam_major_arcsec',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True)
        batch_op.alter_column('type',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
        batch_op.alter_column('created_at',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=False)
        batch_op.alter_column('ms_path',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
        batch_op.alter_column('path',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    with op.batch_alter_table('hdf5_file_index', schema=None) as batch_op:
        batch_op.alter_column('indexed_at',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=False)
        batch_op.alter_column('modified_time',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True)
        batch_op.alter_column('timestamp_mjd',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True)
        batch_op.alter_column('timestamp_iso',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('subband_code',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
        batch_op.alter_column('group_id',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
        batch_op.alter_column('filename',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
        batch_op.alter_column('path',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=True)

    with op.batch_alter_table('dead_letter_queue', schema=None) as batch_op:
        batch_op.alter_column('resolved_at',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True)
        batch_op.alter_column('status',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True,
               existing_server_default=sa.text("'pending'"))
        batch_op.alter_column('created_at',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=False)
        batch_op.alter_column('error_type',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
        batch_op.alter_column('operation',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
        batch_op.alter_column('component',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    with op.batch_alter_table('calibrator_transits', schema=None) as batch_op:
        batch_op.alter_column('updated_at',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=False)
        batch_op.alter_column('calculated_at',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=False)
        batch_op.alter_column('pb_response',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True)
        batch_op.alter_column('delta_minutes',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True)
        batch_op.alter_column('group_mid_iso',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('group_id',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('transit_iso',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
        batch_op.alter_column('transit_mjd',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=False)
        batch_op.alter_column('calibrator_name',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)

    with op.batch_alter_table('batch_jobs', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
        batch_op.alter_column('created_at',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=False)
        batch_op.alter_column('type',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    with op.batch_alter_table('batch_job_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('completed_at', sa.REAL(), nullable=True))
        batch_op.add_column(sa.Column('data_id', sa.TEXT(), server_default=sa.text('(NULL)'), nullable=True))
        batch_op.create_index(batch_op.f('idx_batch_items_ms_path'), ['ms_path'], unique=False)
        batch_op.create_index(batch_op.f('idx_batch_items_batch_id'), ['batch_id'], unique=False)
        batch_op.alter_column('started_at',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True)
        batch_op.alter_column('status',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
        batch_op.alter_column('ms_path',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    op.create_table('data_registry',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('data_type', sa.TEXT(), nullable=False),
    sa.Column('data_id', sa.TEXT(), nullable=False),
    sa.Column('base_path', sa.TEXT(), nullable=False),
    sa.Column('status', sa.TEXT(), server_default=sa.text("'staging'"), nullable=False),
    sa.Column('stage_path', sa.TEXT(), nullable=False),
    sa.Column('published_path', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.REAL(), nullable=False),
    sa.Column('staged_at', sa.REAL(), nullable=False),
    sa.Column('published_at', sa.REAL(), nullable=True),
    sa.Column('publish_mode', sa.TEXT(), nullable=True),
    sa.Column('metadata_json', sa.TEXT(), nullable=True),
    sa.Column('qa_status', sa.TEXT(), nullable=True),
    sa.Column('validation_status', sa.TEXT(), nullable=True),
    sa.Column('finalization_status', sa.TEXT(), server_default=sa.text("'pending'"), nullable=True),
    sa.Column('auto_publish_enabled', sa.INTEGER(), server_default=sa.text('1'), nullable=True),
    sa.Column('publish_attempts', sa.INTEGER(), server_default=sa.text('0'), nullable=True),
    sa.Column('publish_error', sa.TEXT(), nullable=True),
    sa.Column('photometry_status', sa.TEXT(), server_default=sa.text('(NULL)'), nullable=True),
    sa.Column('photometry_job_id', sa.TEXT(), server_default=sa.text('(NULL)'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('data_id'),
    sa.UniqueConstraint('data_type', 'data_id')
    )
    with op.batch_alter_table('data_registry', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_data_registry_type_status'), ['data_type', 'status'], unique=False)
        batch_op.create_index(batch_op.f('idx_data_registry_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('idx_data_registry_published_at'), ['published_at'], unique=False)
        batch_op.create_index(batch_op.f('idx_data_registry_finalization'), ['finalization_status'], unique=False)

    op.create_table('jobs',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('type', sa.TEXT(), nullable=False),
    sa.Column('status', sa.TEXT(), server_default=sa.text("'pending'"), nullable=False),
    sa.Column('ms_path', sa.TEXT(), nullable=False),
    sa.Column('params', sa.TEXT(), nullable=True),
    sa.Column('logs', sa.TEXT(), nullable=True),
    sa.Column('artifacts', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.REAL(), nullable=False),
    sa.Column('started_at', sa.REAL(), nullable=True),
    sa.Column('finished_at', sa.REAL(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_jobs_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('idx_jobs_created'), ['created_at'], unique=False)

    op.create_table('mosaics',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('path', sa.TEXT(), nullable=False),
    sa.Column('name', sa.TEXT(), nullable=False),
    sa.Column('created_at', sa.REAL(), nullable=False),
    sa.Column('start_mjd', sa.REAL(), nullable=False),
    sa.Column('end_mjd', sa.REAL(), nullable=False),
    sa.Column('integration_sec', sa.REAL(), nullable=True),
    sa.Column('n_images', sa.INTEGER(), nullable=True),
    sa.Column('center_ra_deg', sa.REAL(), nullable=True),
    sa.Column('center_dec_deg', sa.REAL(), nullable=True),
    sa.Column('dec_min_deg', sa.REAL(), nullable=True),
    sa.Column('dec_max_deg', sa.REAL(), nullable=True),
    sa.Column('noise_jy', sa.REAL(), nullable=True),
    sa.Column('beam_major_arcsec', sa.REAL(), nullable=True),
    sa.Column('beam_minor_arcsec', sa.REAL(), nullable=True),
    sa.Column('beam_pa_deg', sa.REAL(), nullable=True),
    sa.Column('n_sources', sa.INTEGER(), nullable=True),
    sa.Column('thumbnail_path', sa.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('path')
    )
    with op.batch_alter_table('mosaics', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_mosaics_mjd'), ['start_mjd', 'end_mjd'], unique=False)
        batch_op.create_index(batch_op.f('idx_mosaics_created'), ['created_at'], unique=False)

    op.create_table('cross_matches',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('source_id', sa.TEXT(), nullable=False),
    sa.Column('catalog_type', sa.TEXT(), nullable=False),
    sa.Column('catalog_source_id', sa.TEXT(), nullable=True),
    sa.Column('separation_arcsec', sa.REAL(), nullable=False),
    sa.Column('dra_arcsec', sa.REAL(), nullable=True),
    sa.Column('ddec_arcsec', sa.REAL(), nullable=True),
    sa.Column('detected_flux_jy', sa.REAL(), nullable=True),
    sa.Column('catalog_flux_jy', sa.REAL(), nullable=True),
    sa.Column('flux_ratio', sa.REAL(), nullable=True),
    sa.Column('match_quality', sa.TEXT(), nullable=True),
    sa.Column('match_method', sa.TEXT(), server_default=sa.text("'basic'"), nullable=True),
    sa.Column('master_catalog_id', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.REAL(), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['variability_stats.source_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_id', 'catalog_type')
    )
    with op.batch_alter_table('cross_matches', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_cross_matches_source'), ['source_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_cross_matches_quality'), ['match_quality'], unique=False)
        batch_op.create_index(batch_op.f('idx_cross_matches_master'), ['master_catalog_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_cross_matches_created'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('idx_cross_matches_catalog'), ['catalog_type'], unique=False)

    op.create_table('data_tags',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('data_id', sa.TEXT(), nullable=False),
    sa.Column('tag', sa.TEXT(), nullable=False),
    sa.ForeignKeyConstraint(['data_id'], ['data_registry.data_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('data_id', 'tag')
    )
    with op.batch_alter_table('data_tags', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_data_tags_data_id'), ['data_id'], unique=False)

    op.create_table('transient_lightcurves',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('candidate_id', sa.INTEGER(), nullable=False),
    sa.Column('mjd', sa.REAL(), nullable=False),
    sa.Column('flux_mjy', sa.REAL(), nullable=False),
    sa.Column('flux_err_mjy', sa.REAL(), nullable=True),
    sa.Column('frequency_ghz', sa.REAL(), nullable=True),
    sa.Column('mosaic_id', sa.INTEGER(), nullable=True),
    sa.Column('image_path', sa.TEXT(), nullable=True),
    sa.Column('measured_at', sa.REAL(), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['transient_candidates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('transient_lightcurves', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_lightcurves_candidate'), ['candidate_id', 'mjd'], unique=False)

    op.create_table('astrometric_residuals',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('solution_id', sa.INTEGER(), nullable=False),
    sa.Column('source_ra_deg', sa.REAL(), nullable=False),
    sa.Column('source_dec_deg', sa.REAL(), nullable=False),
    sa.Column('reference_ra_deg', sa.REAL(), nullable=False),
    sa.Column('reference_dec_deg', sa.REAL(), nullable=False),
    sa.Column('ra_offset_mas', sa.REAL(), nullable=False),
    sa.Column('dec_offset_mas', sa.REAL(), nullable=False),
    sa.Column('separation_mas', sa.REAL(), nullable=False),
    sa.Column('source_flux_mjy', sa.REAL(), nullable=True),
    sa.Column('reference_flux_mjy', sa.REAL(), nullable=True),
    sa.Column('measured_at', sa.REAL(), nullable=False),
    sa.ForeignKeyConstraint(['solution_id'], ['astrometric_solutions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('astrometric_residuals', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_residuals_solution'), ['solution_id'], unique=False)

    op.create_table('transient_alerts',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('candidate_id', sa.INTEGER(), nullable=False),
    sa.Column('alert_level', sa.TEXT(), nullable=False),
    sa.Column('alert_message', sa.TEXT(), nullable=False),
    sa.Column('created_at', sa.REAL(), nullable=False),
    sa.Column('acknowledged', sa.INTEGER(), server_default=sa.text('0'), nullable=True),
    sa.Column('acknowledged_at', sa.REAL(), nullable=True),
    sa.Column('acknowledged_by', sa.TEXT(), nullable=True),
    sa.Column('follow_up_status', sa.TEXT(), nullable=True),
    sa.Column('notes', sa.TEXT(), nullable=True),
    sa.ForeignKeyConstraint(['candidate_id'], ['transient_candidates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('transient_alerts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_alerts_status'), ['acknowledged', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('idx_alerts_level'), ['alert_level', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('idx_alerts_candidate'), ['candidate_id'], unique=False)

    op.create_table('regions',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('name', sa.TEXT(), nullable=False),
    sa.Column('type', sa.TEXT(), nullable=False),
    sa.Column('coordinates', sa.TEXT(), nullable=False),
    sa.Column('image_path', sa.TEXT(), nullable=False),
    sa.Column('created_at', sa.REAL(), nullable=False),
    sa.Column('created_by', sa.TEXT(), nullable=True),
    sa.Column('updated_at', sa.REAL(), nullable=True),
    sa.ForeignKeyConstraint(['image_path'], ['images.path'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('regions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_regions_type'), ['type'], unique=False)
        batch_op.create_index(batch_op.f('idx_regions_image'), ['image_path'], unique=False)
        batch_op.create_index(batch_op.f('idx_regions_created'), ['created_at'], unique=False)

    op.create_table('calibration_qa',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('ms_path', sa.TEXT(), nullable=False),
    sa.Column('job_id', sa.INTEGER(), nullable=False),
    sa.Column('k_metrics', sa.TEXT(), nullable=True),
    sa.Column('bp_metrics', sa.TEXT(), nullable=True),
    sa.Column('g_metrics', sa.TEXT(), nullable=True),
    sa.Column('overall_quality', sa.TEXT(), nullable=True),
    sa.Column('flags_total', sa.REAL(), nullable=True),
    sa.Column('per_spw_stats', sa.TEXT(), nullable=True),
    sa.Column('timestamp', sa.REAL(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('calibration_qa', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_cal_qa_ms_path'), ['ms_path'], unique=False)

    op.create_table('variability_stats',
    sa.Column('source_id', sa.TEXT(), nullable=True),
    sa.Column('ra_deg', sa.REAL(), nullable=False),
    sa.Column('dec_deg', sa.REAL(), nullable=False),
    sa.Column('nvss_flux_mjy', sa.REAL(), nullable=True),
    sa.Column('n_obs', sa.INTEGER(), server_default=sa.text('0'), nullable=True),
    sa.Column('mean_flux_mjy', sa.REAL(), nullable=True),
    sa.Column('std_flux_mjy', sa.REAL(), nullable=True),
    sa.Column('min_flux_mjy', sa.REAL(), nullable=True),
    sa.Column('max_flux_mjy', sa.REAL(), nullable=True),
    sa.Column('chi2_nu', sa.REAL(), nullable=True),
    sa.Column('sigma_deviation', sa.REAL(), nullable=True),
    sa.Column('eta_metric', sa.REAL(), nullable=True),
    sa.Column('last_measured_at', sa.REAL(), nullable=True),
    sa.Column('last_mjd', sa.REAL(), nullable=True),
    sa.Column('updated_at', sa.REAL(), nullable=False),
    sa.PrimaryKeyConstraint('source_id')
    )
    with op.batch_alter_table('variability_stats', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_variability_sigma'), ['sigma_deviation'], unique=False)
        batch_op.create_index(batch_op.f('idx_variability_last_mjd'), ['last_mjd'], unique=False)
        batch_op.create_index(batch_op.f('idx_variability_eta'), ['eta_metric'], unique=False)
        batch_op.create_index(batch_op.f('idx_variability_chi2'), ['chi2_nu'], unique=False)

    op.create_table('data_relationships',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('parent_data_id', sa.TEXT(), nullable=False),
    sa.Column('child_data_id', sa.TEXT(), nullable=False),
    sa.Column('relationship_type', sa.TEXT(), nullable=False),
    sa.ForeignKeyConstraint(['child_data_id'], ['data_registry.data_id'], ),
    sa.ForeignKeyConstraint(['parent_data_id'], ['data_registry.data_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('parent_data_id', 'child_data_id', 'relationship_type')
    )
    with op.batch_alter_table('data_relationships', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_data_relationships_parent'), ['parent_data_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_data_relationships_child'), ['child_data_id'], unique=False)

    op.create_table('alert_history',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('source_id', sa.TEXT(), nullable=False),
    sa.Column('alert_type', sa.TEXT(), nullable=False),
    sa.Column('severity', sa.TEXT(), nullable=False),
    sa.Column('message', sa.TEXT(), nullable=False),
    sa.Column('sent_at', sa.REAL(), nullable=False),
    sa.Column('channel', sa.TEXT(), nullable=True),
    sa.Column('success', sa.INTEGER(), server_default=sa.text('1'), nullable=True),
    sa.Column('error_msg', sa.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('alert_history', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_alert_type'), ['alert_type'], unique=False)
        batch_op.create_index(batch_op.f('idx_alert_source'), ['source_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_alert_sent'), ['sent_at'], unique=False)

    op.create_table('ese_candidates',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('source_id', sa.TEXT(), nullable=False),
    sa.Column('flagged_at', sa.REAL(), nullable=False),
    sa.Column('flagged_by', sa.TEXT(), server_default=sa.text("'auto'"), nullable=True),
    sa.Column('significance', sa.REAL(), nullable=False),
    sa.Column('flag_type', sa.TEXT(), nullable=False),
    sa.Column('notes', sa.TEXT(), nullable=True),
    sa.Column('status', sa.TEXT(), server_default=sa.text("'active'"), nullable=True),
    sa.Column('investigated_at', sa.REAL(), nullable=True),
    sa.Column('dismissed_at', sa.REAL(), nullable=True),
    sa.ForeignKeyConstraint(['source_id'], ['variability_stats.source_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ese_candidates', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_ese_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('idx_ese_source'), ['source_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_ese_flagged'), ['flagged_at'], unique=False)

    op.create_table('image_qa',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('ms_path', sa.TEXT(), nullable=False),
    sa.Column('job_id', sa.INTEGER(), nullable=False),
    sa.Column('image_path', sa.TEXT(), nullable=False),
    sa.Column('rms_noise', sa.REAL(), nullable=True),
    sa.Column('peak_flux', sa.REAL(), nullable=True),
    sa.Column('dynamic_range', sa.REAL(), nullable=True),
    sa.Column('beam_major', sa.REAL(), nullable=True),
    sa.Column('beam_minor', sa.REAL(), nullable=True),
    sa.Column('beam_pa', sa.REAL(), nullable=True),
    sa.Column('num_sources', sa.INTEGER(), nullable=True),
    sa.Column('thumbnail_path', sa.TEXT(), nullable=True),
    sa.Column('overall_quality', sa.TEXT(), nullable=True),
    sa.Column('timestamp', sa.REAL(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('image_qa', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_img_qa_ms_path'), ['ms_path'], unique=False)

    op.create_table('astrometric_solutions',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('mosaic_id', sa.INTEGER(), nullable=True),
    sa.Column('image_path', sa.TEXT(), nullable=True),
    sa.Column('reference_catalog', sa.TEXT(), nullable=False),
    sa.Column('n_matches', sa.INTEGER(), nullable=False),
    sa.Column('ra_offset_mas', sa.REAL(), nullable=False),
    sa.Column('dec_offset_mas', sa.REAL(), nullable=False),
    sa.Column('ra_offset_err_mas', sa.REAL(), nullable=True),
    sa.Column('dec_offset_err_mas', sa.REAL(), nullable=True),
    sa.Column('rotation_deg', sa.REAL(), nullable=True),
    sa.Column('scale_factor', sa.REAL(), nullable=True),
    sa.Column('rms_residual_mas', sa.REAL(), nullable=True),
    sa.Column('applied', sa.INTEGER(), server_default=sa.text('0'), nullable=True),
    sa.Column('computed_at', sa.REAL(), nullable=False),
    sa.Column('applied_at', sa.REAL(), nullable=True),
    sa.Column('notes', sa.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('astrometric_solutions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_astrometry_mosaic'), ['mosaic_id', 'computed_at'], unique=False)
        batch_op.create_index(batch_op.f('idx_astrometry_applied'), ['applied', 'computed_at'], unique=False)

    # ### end Alembic commands ###
